<a href="https://colab.research.google.com/github/AIVIETNAM-AIO-HUYTRUONG/AIO/blob/aio/M4-Foundation-DL/Python-based-DS/M04W01%20-%20Data%20Cleaning%26Transformation%20Using%20Pandas/data_transformation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget -q \
    "https://raw.githubusercontent.com/AIVIETNAM-AIO-HUYTRUONG/AIO/refs/heads/aio/helpers/dataset_helper.py" \
    -O /content/helper.py

%run /content/helper.py

In [ ]:
# https://raw.githubusercontent.com/AIVIETNAM-AIO-HUYTRUONG/AIO/refs/heads/aio/M4-Foundation-DL/Python-based-DS/Data/data_transformation_don_hang_clean.csv
CSV_URL = input("Paste CSV URL: ").strip()

df = load_csv_from_url(
    url=CSV_URL,
    data_dir="/content/data",
    filename="data_transformation_don_hang_clean.csv"
)

df.head()

Paste CSV URL: https://raw.githubusercontent.com/AIVIETNAM-AIO-HUYTRUONG/AIO/refs/heads/aio/M4-Foundation-DL/Python-based-DS/Data/data_transformation_don_hang_clean.csv
Downloading dataset from:
https://raw.githubusercontent.com/AIVIETNAM-AIO-HUYTRUONG/AIO/refs/heads/aio/M4-Foundation-DL/Python-based-DS/Data/data_transformation_don_hang_clean.csv
Dataset downloaded successfully:
/content/data/data_transformation_don_hang_clean.csv
Dataset loaded successfully:
- Path: /content/data/data_transformation_don_hang_clean.csv
- Rows: 5
- Columns: 5

  OrderID Customer     City  Quantity   OrderDate
0    O101       An      HCM         2  2026-09-01
1    O102     Binh       HN         1  2026-09-02
2    O103      Chi      HCM         2  2026-09-03
3    O104     Dung  Da Nang         3  2026-09-04
4    O105       Em      HCM         1  2026-09-05

# From Cleaned Data to an Analysis Question
- Câu hỏi phân tích: Tổng số lượng sản phẩm được đặt ở mỗi thành phố là bao nhiêu?

In [ ]:
df_clean = pd.read_csv("/content/data/data_transformation_don_hang_clean.csv")
df_clean = df_clean.set_index("OrderID")
df_clean.head()

        Customer     City  Quantity   OrderDate
OrderID
O101          An      HCM         2  2026-09-01
O102        Binh       HN         1  2026-09-02
O103         Chi      HCM         2  2026-09-03
O104        Dung  Da Nang         3  2026-09-04
O105          Em      HCM         1  2026-09-05

# Select, Rename and Remove Columns

- Chỉ giữ lại các cột cần thiệt và đổi tên cho rõ nghĩa hơn trong bảng phân tích.

In [ ]:
df_analysis = df_clean[['City', "Quantity"]].copy()
df_analysis = df_analysis.rename(columns = {"Quantity":"Items"})
df_analysis

            City  Items
OrderID
O101         HCM      2
O102          HN      1
O103         HCM      2
O104     Da Nang      3
O105         HCM      1

# Group Data with groupby()

- `groupby()` tạo nhóm, `sum()` tính tổng cho từng nhóm.

In [ ]:
city_items = df_analysis.groupby("City")["Items"].sum()
city_items

City
Da Nang    3
HCM        5
HN         1
Name: Items, dtype: int64

# Create a Derived Column
- Một cột phát sinh tính toán thông tin mới từ các giá trị hiện có

In [ ]:
average_items = df_analysis['Items'].mean()
df_analysis["AboveAverage"] = df_analysis['Items'] > average_items
df_analysis

            City  Items  AboveAverage
OrderID
O101         HCM      2          True
O102          HN      1         False
O103         HCM      2          True
O104     Da Nang      3          True
O105         HCM      1         False

# Filter and Sort Rows
- Filter giữa lại các dòng thảo mãn điều kiện.
- Sort thay đổi thứ tự các dòng.

In [ ]:
filtered_orders = df_analysis.loc[df_analysis['AboveAverage'],["City", "Items"]]
sorted_orders = filtered_orders.sort_values("Items", ascending=False)
sorted_orders

            City  Items
OrderID
O104     Da Nang      3
O101         HCM      2
O103         HCM      2

# Summarize Data with agg()
- `agg()` tính nhiều chỉ số tổng hợp cùng lúc cho mỗi nhóm.

In [ ]:
df_analysis

            City  Items  AboveAverage
OrderID
O101         HCM      2          True
O102          HN      1         False
O103         HCM      2          True
O104     Da Nang      3          True
O105         HCM      1         False

In [ ]:
df_analysis.groupby("City").agg(
    OrderCount = ("Items", "size"),
    TotalItems = ("Items", "sum"),
    AverageItems = ("Items", "mean")
)

         OrderCount  TotalItems  AverageItems
City
Da Nang           1           3      3.000000
HCM               3           5      1.666667
HN                1           1      1.000000