<a href="https://colab.research.google.com/github/AIVIETNAM-AIO-HUYTRUONG/AIO/blob/aio/M4-Foundation-DL/Python-based-DS/M04W01%20-%20Data%20Cleaning%26Transformation%20Using%20Pandas/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget -q \
    "https://raw.githubusercontent.com/AIVIETNAM-AIO-HUYTRUONG/AIO/refs/heads/aio/helpers/dataset_helper.py" \
    -O /content/helper.py

%run /content/helper.py

In [ ]:
# https://raw.githubusercontent.com/AIVIETNAM-AIO-HUYTRUONG/AIO/refs/heads/aio/M4-Foundation-DL/Python-based-DS/Data/practice_diem_thi.csv
CSV_URL = input("Paste CSV URL: ").strip()

df = load_csv_from_url(
    url=CSV_URL,
    data_dir="/content/data",
    filename="practice_diem_thi.csv"
)

df.head()

Paste CSV URL: https://raw.githubusercontent.com/AIVIETNAM-AIO-HUYTRUONG/AIO/refs/heads/aio/M4-Foundation-DL/Python-based-DS/Data/practice_diem_thi.csv
Downloading dataset from:
https://raw.githubusercontent.com/AIVIETNAM-AIO-HUYTRUONG/AIO/refs/heads/aio/M4-Foundation-DL/Python-based-DS/Data/practice_diem_thi.csv
Dataset downloaded successfully:
/content/data/practice_diem_thi.csv
Dataset loaded successfully:
- Path: /content/data/practice_diem_thi.csv
- Rows: 8
- Columns: 6

  StudentID Class     Score AttendanceRate      ExamDate     Status
0      S101  10A1       8.5            95%    2026-09-01  Completed
1      S102  10a1       7.0            90%    2026/09/02  completed
2      S103  10A2       NaN            88%    03-09-2026     Absent
3      S104  10A2  9 points            92%  Sep 04, 2026  Completed
4      S104  10A2  9 points            92%  Sep 04, 2026  Completed

# Bài toán:
- Một giáo viên cần so sánh kết quả thi giữa các lớp
- Lớp nào có điểm trung bình cao nhất trong số các bài thi đã hoàn thành?
- Có bao nhiêu học sinh đậu.

In [ ]:
exam_results = pd.read_csv("/content/data/practice_diem_thi.csv")
exam_results

  StudentID  Class     Score AttendanceRate      ExamDate     Status
0      S101   10A1       8.5            95%    2026-09-01  Completed
1      S102   10a1       7.0            90%    2026/09/02  completed
2      S103   10A2       NaN            88%    03-09-2026     Absent
3      S104   10A2  9 points            92%  Sep 04, 2026  Completed
4      S104   10A2  9 points            92%  Sep 04, 2026  Completed
5      S105  10 A1       4.5            85%    2026-09-05  Completed
6      S106   10A2       6.5            89%    2026-09-06  COMPLETED
7      S107   10A3       5.5            80%    2026-09-07  Completed

# Indentify Data Quality Issues
- Kiểm tra data và các value duy nhất để phát hiện vấn đề về chất lượng data.

In [ ]:
exam_results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   StudentID       8 non-null      object
 1   Class           8 non-null      object
 2   Score           7 non-null      object
 3   AttendanceRate  8 non-null      object
 4   ExamDate        8 non-null      object
 5   Status          8 non-null      object
dtypes: object(6)
memory usage: 516.0+ bytes

In [ ]:
exam_results['Class'].unique()

array(['10A1', '10a1', '10A2', '10 A1', '10A3'], dtype=object)

In [ ]:
exam_results['Score'].unique()

array(['8.5', '7.0', nan, '9 points', '4.5', '6.5', '5.5'], dtype=object)

In [ ]:
exam_results['ExamDate'].unique()

array(['2026-09-01', '2026/09/02', '03-09-2026', 'Sep 04, 2026',
       '2026-09-05', '2026-09-06', '2026-09-07'], dtype=object)

In [ ]:
exam_results['Status'].unique()

array(['Completed', 'completed', 'Absent', 'COMPLETED'], dtype=object)

#  Remove Duplicate Rows
- `duplicated()` đánh dấu các bản ghi lặp lại sau bản ghi đầu tiên.
- `drop_duplicates()` giữ lại bản ghi đầu tiên.

In [ ]:
duplicate_mask =  exam_results.duplicated()
exam_results[duplicate_mask]

  StudentID Class     Score AttendanceRate      ExamDate     Status
4      S104  10A2  9 points            92%  Sep 04, 2026  Completed

In [ ]:
df_clean = exam_results.drop_duplicates().copy()
df_clean

  StudentID  Class     Score AttendanceRate      ExamDate     Status
0      S101   10A1       8.5            95%    2026-09-01  Completed
1      S102   10a1       7.0            90%    2026/09/02  completed
2      S103   10A2       NaN            88%    03-09-2026     Absent
3      S104   10A2  9 points            92%  Sep 04, 2026  Completed
5      S105  10 A1       4.5            85%    2026-09-05  Completed
6      S106   10A2       6.5            89%    2026-09-06  COMPLETED
7      S107   10A3       5.5            80%    2026-09-07  Completed

In [ ]:
df_clean.duplicated().sum()

np.int64(0)

# Standardize Text Labels

- Áp dụng một quy tắc chuẩn hóa cho từng cột để tránh một lớp hoặc trạng thái bị tách thành nhiều nhóm khác nhau.

In [ ]:
df_clean['Class'].unique()

array(['10A1', '10a1', '10A2', '10 A1', '10A3'], dtype=object)

In [ ]:
df_clean['Class'] = df_clean['Class'].str.replace(" ", "", regex=False).str.upper()
df_clean['Class'].unique()

array(['10A1', '10A2', '10A3'], dtype=object)

In [ ]:
df_clean["Status"].unique()

array(['Completed', 'completed', 'Absent', 'COMPLETED'], dtype=object)

In [ ]:
df_clean["Status"] = df_clean["Status"].str.title()
df_clean["Status"].unique()

array(['Completed', 'Absent'], dtype=object)

# Convert Data Type

- Chuyển Scorce sang dạng số và ExamDate sang dạng ngày tháng.

In [ ]:
df_clean["ExamDate"] = pd.to_datetime(
    df_clean["ExamDate"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)
df_clean["ExamDate"].unique()

<DatetimeArray>
['2026-09-01 00:00:00', '2026-09-02 00:00:00', '2026-09-03 00:00:00',
 '2026-09-04 00:00:00', '2026-09-05 00:00:00', '2026-09-06 00:00:00',
 '2026-09-07 00:00:00']
Length: 7, dtype: datetime64[ns]

In [ ]:
df_clean["Score"] = pd.to_numeric(
    df_clean["Score"].astype("string").str.replace("points", "", regex=False),
    errors="coerce"
)

df_clean["Score"].unique()

<FloatingArray>
[8.5, 7.0, <NA>, 9.0, 4.5, 6.5, 5.5]
Length: 7, dtype: Float64

# Handle the Missing Score

- Giá trị Score bị thiếu của học sinh vắng thi được giữa nguyên (không xóa vì phù hớp với Status).

In [ ]:
absent_mask = df_clean["Status"].eq("Absent")
df_clean.loc[absent_mask, "Score"]

2    <NA>
Name: Score, dtype: Float64

In [ ]:
df_clean.loc[absent_mask, "Score"].isna().all()

np.True_

# Validate the Cleaned Data
- Chạy đầy đủ các kiểm tra để xác nhận dữ liệu đã sẵn sàng cho phân tích

In [ ]:
df_clean.shape

(7, 6)

In [ ]:
df_clean.duplicated().sum()

np.int64(0)

In [ ]:
df_clean["StudentID"].is_unique

True

In [ ]:
sorted(df_clean["Class"].unique())

['10A1', '10A2', '10A3']

In [ ]:
sorted(df_clean["Status"].unique())

['Absent', 'Completed']

In [ ]:
df_clean[["Score", "ExamDate"]].dtypes

Score              Float64
ExamDate    datetime64[ns]
dtype: object

# Prepare Data for Analysis
- Lọc chỉ giữ các bài thi đã hoàn thành (Completed), sau đó chọn các cột cần thiết.

In [ ]:
completed_column = df_clean['Status'].eq("Completed")

df_analysis = df_clean.loc[completed_column, ["StudentID","Class", "Score", "ExamDate"]].copy()
df_analysis

  StudentID Class  Score   ExamDate
0      S101  10A1    8.5 2026-09-01
1      S102  10A1    7.0 2026-09-02
3      S104  10A2    9.0 2026-09-04
5      S105  10A1    4.5 2026-09-05
6      S106  10A2    6.5 2026-09-06
7      S107  10A3    5.5 2026-09-07

# Create the Passed Column
- Quy tắc: Passed = Score >= 5.

In [ ]:
df_analysis["Passed"] = df_analysis['Score'].ge(5)
df_analysis

  StudentID Class  Score   ExamDate  Passed
0      S101  10A1    8.5 2026-09-01    True
1      S102  10A1    7.0 2026-09-02    True
3      S104  10A2    9.0 2026-09-04    True
5      S105  10A1    4.5 2026-09-05   False
6      S106  10A2    6.5 2026-09-06    True
7      S107  10A3    5.5 2026-09-07    True

# Summarize Results by Class
- Nhóm học sinh theo lớp, tính điểm trung bình và số học sinh đạt bằng `agg()`.

In [ ]:
class_summary = df_analysis.groupby("Class").agg(
    AverageScore=("Score", "mean"),
    NumberOfPassed=("Passed", "sum")
).round(2)

class_summary

       AverageScore  NumberOfPassed
Class
10A1           6.67               2
10A2           7.75               2
10A3            5.5               1